### ISSUE TITLE
Picker value not always saved

### ISSUE THREAD

**Issue by organicglenn** [imulus/uWestFest#13]
I am seeing this intermittently...the worst kind of bug.
Changes to the value of the UrlPicker are not always saved.  I can set the value initially to any of the three types and Save/Publishing successfully.  But if I try to make an edit, the original value persists...sometimes.  I'm getting inconsistent test results.  Maybe it doesn't matter whether I'm adding or editing.  I've tested 100 times and I still can't draw a clear conclusion so wanted to pass it along.

**Comment by kgiszewski** [comment]
Closing as this is probably a legacy issue.
