### ISSUE TITLE
How do you call the newWindow property?

### ISSUE THREAD

**Issue by wroughtec** [imulus/uWestFest#15]
I might have missed something but I cannot seem to get the newWindow property to work.

How should I call it in something like:
```
@foreach (var call in action) {
     var link = call.GetValue<UrlPicker.Umbraco.Models.UrlPicker>("urlPicker");
     if(link != null && !string.IsNullOrWhiteSpace(link.Name)) {
     <a href="@link.Url" class="btn" target="???" title="@link.Name">@link.Name</a>
}
```
I have tried @link.Target and @link.NewWindow and after a quick look through the source I cannot see what it could be any assistance would be very welcome thanks.

**Comment by kgiszewski** [comment]
Newest version uses `.Target`. Closing as this has been addressed.
