### ISSUE TITLE
UrlPicker returns null when media selected

### ISSUE THREAD

**Issue by snerpton** [imulus/uWestFest#27]
When media has been selected a null object is returned. URL and content fine.

All worked fine with:

- Umbraco: 7.2.1
- UrlPicker: 0.12.0

Following upgrade to:

- Umbraco: 7.2.8
- UrlPicker: 0.14.0

Url and Content fine, but media selection always returns null.

Reverting to `UrlPicker v0.12.0` seemed to fix the problem. Upgrade to `UrlPicker v 0.13.0` introduced the issue, so I guess there is a breaking change in that release?

Issue first reported at: https://our.umbraco.org/projects/backoffice-extensions/urlpicker/issues/71426-urlpicker-failing-for-selecting-media

**Comment by kgiszewski** [comment]
Ironically I ran into this yesterday. Thank you for confirming this. I will have to investigate.


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by kgiszewski** [comment]
Fixed and you can update via the normal methods.

**Comment by snerpton** [comment]
Just installed v0.14.1 and all works fine for me. Thanks for the quick fix @kgiszewski.
