### ISSUE TITLE
UrlPicker class conflicts with the namespace

### ISSUE THREAD

**Issue by kipusoep** [imulus/uWestFest#28]
If I want to use the class UrlPicker inside my own code, I get the following error:
```CS0118	'UrlPicker' is a namespace but is used like a type```
This is obvious, but really annoying. Renaming the class would be a breaking change, but how about adding a IUrlPicker interface for the model, so we can use the interface without a problem?

**Comment by kgiszewski** [comment]
Yep, agree it's annoying. I'm not able to spend the time on this due to lack of time (sorry).

**Comment by kipusoep** [comment]
No problem @kgiszewski, I know what it's like to have a lot on your plate :-)
