### ISSUE TITLE
NuGet install not overwriting package.manifest?

### ISSUE THREAD

**Issue by tomfulton** [imulus/uWestFest#7]
I ran `install-package UrlPicker` on a site that had 0.9.2 installed manually.

I was prompted to overrite some files, but for some reason it didn't seem to overwrite the `package.manifest`:

![2014-05-16_14-02-21](https://cloud.githubusercontent.com/assets/1396376/3001770/5d9bfde8-dd35-11e3-80b6-86c7eea14299.png)

**Comment by kgiszewski** [comment]
This is old and I'm in the process of updating the grunt stuffs so I'm closing it :)
